jboss:
  image: bzon/jboss-eap:latest
  container_name: jboss
  environment:
   DEFAULT_CONTROLLER_HOST: "${DEFAULT_CONTROLLER_HOST}"
   STANDALONE_SCRIPT_ARGS: "${STANDALONE_SCRIPT_ARGS}"
  ports:
   - "8443:8443"
   - "8080:8080"
   - "9990:9990"
   - "9999:9999"
